services:
  tg-headless-connector:
    image: ghcr.io/twingate-connector/twingate-custom-connector-container:latest  
    privileged: true

    environment:
      - TWINGATE_HOSTNAME=<YOUR_TWINGATE_HOSTNAME>
      - TWINGATE_ACCESS_TOKEN=<ACCESS_TOKEN>
      - TWINGATE_REFRESH_TOKEN=<REFRESH_TOKEN>
      #- TWINGATE_LOG_ANALYTICS=v2 #remove the comment tag on this if you want detailed traffic logging
      #- TWINGATE_LOG_LEVEL=3 #remove the comment tag and set this to 7 if you want debug logging enabled

    tty: true

    restart: unless-stopped